### PR TITLE
Make document addition asynchronous and improve report on it

### LINKED ISSUE #194: error timeout of 5000ms has exceeded on process 3 when waiting a task to be resolved.
Hi - we are using this plugin (which is fantastic) with Gatsby however we've started getting this issue `only` in CI (Gitlab). If I run the build locally on my Mac it is fine which would suggest some kind of resourcing issue?

```
success Building static HTML for pages - 39.268s - 2714/2714 69.12/s
error timeout of 5000ms has exceeded on process 3 when waiting a task to be resolved.
success gatsby-plugin-meilisearch - 9.715s - Failed to index to Meilisearch
success onPostBuild - 10.556s
```

A similar issue (https://github.com/meilisearch/strapi-plugin-meilisearch/issues/337) talks about auto-batching and changing the timeout. Auto-batching is apparently enabled now and there doesn't seem to be any option for changing the timeout with the plugin. I've tried different `batchSize` settings to no avail. We have approx 2,700 documents to index so not a massive amount.

We run the docker version of Meilisearch (v029.2) in ECS Fargate.

```
"gatsby": "4.14.1",
"gatsby-plugin-meilisearch": "^0.2.1",
```

Is there a way to change the timeout or can you advise how I can troubleshoot? 

Many thanks.

### PR DESCRIPTION
**Pull request by bidoubiwa**
# Pull Request

## Related issue
Fixes #194 

## What does this PR do?
- Remove every use of `wait_for_task` to avoid a timeout and to fasten the build time.
- Add logging providing the tasks uids of every batch of documents send to Meilisearch

Output example:
```
success Delete previous page data - 0.001s
success Send documents to Meilisearch - 0.014s - Adding 10 document(s) to
Meilisearch, task uid : "2063".
success Send documents to Meilisearch - 0.063s - Adding 10 document(s) to
Meilisearch, task uid : "2064".
success Send documents to Meilisearch - 0.059s - Adding 10 document(s) to
Meilisearch, task uid : "2065".
success Send documents to Meilisearch - 0.079s - Adding 10 document(s) to
Meilisearch, task uid : "2066".
success Send documents to Meilisearch - 0.023s - Adding 9 document(s) to
Meilisearch, task uid : "2067".
success gatsby-plugin-meilisearch - 0.350s - Documents are send to Meilisearch,
track the indexing progress using the tasks uids.
```

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -63,45 +63,53 @@ exports.onPostBuild = async function ({ graphql, reporter }, config) {
...
-        )
+        const tasks = []
 
-        if (enqueuedUpdates.length === 0) {
-          throw getErrorMsg(
-            'Nothing has been indexed to Meilisearch. Make sure your documents are transformed into an array of objects'
+        // Send documents in batches of `batchSize`
+        for (let i = 0; i < transformedData.length; i += batchSize) {
+          let documentsActivity = reporter.activityTimer(
+            'Send documents to Meilisearch'
```
Comment (mdubus) [inline gatsby-node.js:81]: I don't get this sentence. Does this mean that documents have been sent to Meilisearch, or that it's currently sending documents to Meilisearch?

File: gatsby-node.js [hunk 2]
```diff
@@ -63,45 +63,53 @@ exports.onPostBuild = async function ({ graphql, reporter }, config) {
...
+            documentsActivity.setStatus(
+              'Failed to send batch of document to Meilisearch'
+            )
           }
+          documentsActivity.end()
+        }
+
+        if (tasks.length === 0) {
+          throw getErrorMsg(
+            'No documents have been indexed to Meilisearch. Make sure your documents are transformed into an array of objects'
```
Comment (mdubus) [inline gatsby-node.js:105]: Are we sure 100% this is the reason the user will encounter by entering here? For example, what if the graphql query fetched 0 documents?

File: gatsby-node.js (hunk 1 above)
Comment (bidoubiwa) [reply gatsby-node.js:81]: That in the loop, documents are sent by batches

File: gatsby-node.js (hunk 2 above)
Comment (bidoubiwa) [reply gatsby-node.js:105]: Indeed, this part of the error should help the user understand that he did not fetch anything from either graphql or that his `transform` function is bad 

> Make sure your documents are transformed into an array of objects'

Since this condition is not introduced in this PR, if we want to change it, it would be better to create a new issue about it!

File: gatsby-node.js (hunk 1 above)
Comment (bidoubiwa) [reply gatsby-node.js:81]: I updated the comment!

**Review by mdubus — APPROVED** [review]
LGTM ✨ 🦕

**Comment by bidoubiwa** [comment]
bors merge
